name: Skyrim Inventory Management Frontend CI

on:
  push:
    branches: [ main, shopping-lists-page-feature-branch ]
  pull_request:
    branches: [ main, shopping-lists-page-feature-branch ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Node Modules
      run: yarn
    - name: lint
      run: yarn lint
    - name: format
      run: yarn format
    - name: Run tests
      run: yarn test
